### ISSUE TITLE
Symbols in the readme

### ISSUE THREAD

**Issue by championballer** [sandeep021/Handwritten-digit-predictor-using-MNIST-data-set#4]
@sandeep021 Are the symbols in the readme along with the Model, Draw and classify digits in Playground Canvas and Creating and Training The Model intentionally present there? If they are, what do they mean? If they aren't, should they be removed? Thanks. :)

**Comment by sandeep021** [comment]
Actually i am trying to put emojis using these symbols in readme which did not worked. They are not intentional ,they should be removed
